db.url=jdbc:mysql://localhost:3306/WEB_SECURITY_LAB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.user=root
#db.password=ENC(TZXwIRP2+BOHAix66sJMY+kK8k9VWtBu)
db.password=ENC(CVU9zJlFLhHFKb19c/1+zg==:s6MZ6GixQUCUYYtZBMFkDQ==)